export const MobileEventType = {
  UNSPECIFIED: 'MOBILE_EVENT_UNSPECIFIED',
  OPENURLREQUEST: 'MOBILE_EVENT_OPEN_URL_REQUEST',
  BACK: 'MOBILE_EVENT_BACK',
  SHAREURLREQUEST: 'MOBILE_EVENT_SHARE_URL_REQUEST',
  CLIPBOARDWRITE: 'MOBILE_EVENT_CLIPBOARD_WRITE',
};
